config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "questions#index"
  resources :questions, only: :index
  post "/questions/search" => "questions#search", as: "questions_search"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
	def index
		@questions = Question.all
	end

	def search
		query = params[:query]
		@questions = Question.where("title iLike '%#{query}%'").or(Question.where("description iLike '%#{query}%'"))
		render json: @questions
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/question_helper.rb
module QuestionHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ajax</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script
        src="https://code.jquery.com/jquery-3.3.1.js"
        integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
        crossorigin="anonymous"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/questions/index.html.erb
<%= form_tag(questions_search_path, id: "form") do %>
	<input type="text" name="query">
	<input type="submit" value="Filter" name="">
<% end %>

<div id="container">
		--------------------------<br>
	<% @questions.each do |q| %>
		<%= q.title %><br>
		<%= q.description %><br>
		--------------------------<br>
	<% end %>
</div>

<script type="text/javascript">
	$("#form").on("submit", function(e) {
		e.preventDefault()
		$.ajax({
			url: $("#form").attr("action"),
			type: $("#form").attr("method"),
			data: $("#form").serialize(),
			success: function(data) {
				let audio = new Audio("https://www.myinstants.com/media/sounds/139-item-catch.mp3")
				audio.play()
				$("#container").html("")
				html = "--------------------------<br>"
				for (let i = 0; i < data.length; i++) {
					// render data into html
					html = html + `${data[i].title}<br>${data[i].description}<br>--------------------------<br>`
				}
				$("#container").html(html)
			}
		})
	})
</script>